### PR TITLE
Carousel for cards

### PR DESCRIPTION
**Pull request by Annageorg**
Hi guys,

Just created 2 types of carousel for you to choose from. One with Bootstrap the other one with react-alice-carousel npm package.
I made sure the images are of the same dimensions. 
I am not sure if this type of carousel was what we wanted, happy to change whatever you think necessary.

### CODE REVIEW

**Comment by Jordan6271** [comment]
They both look great Anna. I think the images may be a little large (each one is a bit bigger than my laptop screen, not sure what size monitor you use), but that's not an issue for now. 

I think I prefer the second carousel (the bootstrap native one) just because I prefer the look of the arrow buttons being on the image itself, closer to the centre of the screen. It's a personal preference thing though, so I'm happy with the other one if you both prefer that.

**Comment by Annageorg** [comment]
> They both look great Anna. I think the images may be a little large (each one is a bit bigger than my laptop screen, not sure what size monitor you use), but that's not an issue for now.
> 
> I think I prefer the second carousel (the bootstrap native one) just because I prefer the look of the arrow buttons being on the image itself, closer to the centre of the screen. It's a personal preference thing though, so I'm happy with the other one if you both prefer that.

I will need help with the display of the images, they do look big on my pc as well. Tried a couple of solutions wasn't able to figure it out. Maybe Mark could help me with that. 
I am happy with either, I do prefer the Bootstrap more too. The alice one has just the added functionality to slide the pictures with the mouse, that's why I included it.

**Comment by Jordan6271** [comment]
> I am happy with either, I do prefer the Bootstrap more too. The alice one has just the added functionality to slide the pictures with the mouse, that's why I included it.

I actually hadn't noticed that, that is pretty neat functionality. I do wonder if it won't be very obvious to the user that it works that way though - maybe the average user is more tech savvy than me when interacting with carousels, however.

**Comment by Annageorg** [comment]
> I actually hadn't noticed that, that is pretty neat functionality. I do wonder if it won't be very obvious to the user that it works that way though - maybe the average user is more tech savvy than me when interacting with carousels, however.

Agree with you on that. If I hadn't made it, I don't know if I would have noticed that. Also, it would be one less package installed, since we are using Bootstrap all over.

**Comment by Annageorg** [comment]
Closed this PR so I can checkout from our new develop to create the carousel component

**Pull request closed without merging**
